export default {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SET_LOADING: "SET_LOADING",
  SET_REFERENCE: "SET_REFERENCE",
  SET_VIEW_LOG: "SET_VIEW_LOG",

  RESET_LOGS: "RESET_LOGS",
  CREATE_LOGS: "CREATE_LOGS",
  READ_LOGS: "READ_LOGS",
  UPDATE_LOGS: "UPDATE_LOGS",
  DELETE_LOGS: "DELETE_LOGS",

  CREATE_EXERCISES: "CREATE_EXERCISES",
  READ_EXERCISES: "READ_EXERCISES",
  UPDATE_EXERCISES: "UPDATE_EXERCISES",
  DELETE_EXERCISES: "DELETE_EXERCISES",
};
